# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: syst

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: syst
    binary: syst
    main: ./cmd/entrypoint/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_ENABLED=1
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=0
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/redjax/syst/internal/version.Version={{.Version}}'
      - -X 'github.com/redjax/syst/internal/version.Commit={{.Commit}}'
      - -X 'github.com/redjax/syst/internal/version.Date={{.Date}}'

archives:
  - formats: 
      - tar.gz
    ## This name template makes the OS and Arch compatible with the results of `uname` on Linux/Mac.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    ## Use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  use: github
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Repository Changes"
      regexp: '^.*?repo(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "Other Changes"
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 5
  filters:
    exclude:
      - "^test:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
